spring.application.name=crudapp
<<<<<<< HEAD
//connected sql
=======
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/?user=springtutorial
spring.datasource.username=springtutorial
spring.datasource.password=springtutorial
>>>>>>> 67c02de (connected mySql)
